import maya

maya.stringTable['y_xgenm_ui_dialogs_xgCreateMaps.kBasedOnAttribute'] = u'Based on attribute'
maya.stringTable['y_xgenm_ui_dialogs_xgCreateMaps.kBlack'] = u'Black'
maya.stringTable['y_xgenm_ui_dialogs_xgCreateMaps.kBlue'] = u'Blue'
maya.stringTable['y_xgenm_ui_dialogs_xgCreateMaps.kCancel'] = u'Cancel'
maya.stringTable['y_xgenm_ui_dialogs_xgCreateMaps.kCreate'] = u'Create'
maya.stringTable['y_xgenm_ui_dialogs_xgCreateMaps.kCreateMap'] = u'Create Map'
maya.stringTable['y_xgenm_ui_dialogs_xgCreateMaps.kGreen'] = u'Green'
maya.stringTable['y_xgenm_ui_dialogs_xgCreateMaps.kGrey'] = u'Grey'
maya.stringTable['y_xgenm_ui_dialogs_xgCreateMaps.kMapName'] = u'Map Name'
maya.stringTable['y_xgenm_ui_dialogs_xgCreateMaps.kMapResolution'] = u'Map Resolution'
maya.stringTable['y_xgenm_ui_dialogs_xgCreateMaps.kMapResolutionAnn'] = u'Resolution of the map in texels per unit'
maya.stringTable['y_xgenm_ui_dialogs_xgCreateMaps.kRed'] = u'Red'
maya.stringTable['y_xgenm_ui_dialogs_xgCreateMaps.kStartColor'] = u'Start Color'
maya.stringTable['y_xgenm_ui_dialogs_xgCreateMaps.kStartColorAnn'] = u'Choose the starting color that the map will begin with.'
maya.stringTable['y_xgenm_ui_dialogs_xgCreateMaps.kTotalResolutionHelp'] = u'Total Resolution: about 7 million texels\n(Better than a 2.8k x 2.8k texture)'
maya.stringTable['y_xgenm_ui_dialogs_xgCreateMaps.kWhite'] = u'White'
