import maya

maya.stringTable['y_xgenm_ui_dialogs_xgImportPreset.kAddPresetToExistingCollection'] = u'Add Description to existing Collection:'
maya.stringTable['y_xgenm_ui_dialogs_xgImportPreset.kCancelImport'] = u'Cancel'
maya.stringTable['y_xgenm_ui_dialogs_xgImportPreset.kCreateNewCollectionForPreset'] = u'Create new Collection named:'
maya.stringTable['y_xgenm_ui_dialogs_xgImportPreset.kFileNameOfPreset'] = u'Preset File Name:'
maya.stringTable['y_xgenm_ui_dialogs_xgImportPreset.kGenerateGuides'] = u'Generate Guides By:'
maya.stringTable['y_xgenm_ui_dialogs_xgImportPreset.kGrooming'] = u'Grooming'
maya.stringTable['y_xgenm_ui_dialogs_xgImportPreset.kGuideOptionForPreset'] = u'Guide Based Preset Options:'
maya.stringTable['y_xgenm_ui_dialogs_xgImportPreset.kGuideOrientionTransfer'] = u'Guide Orientation:'
maya.stringTable['y_xgenm_ui_dialogs_xgImportPreset.kGuideTranferForPreset'] = u'Guide Transfer method:'
maya.stringTable['y_xgenm_ui_dialogs_xgImportPreset.kImport'] = u'Import'
maya.stringTable['y_xgenm_ui_dialogs_xgImportPreset.kImportPresetFail'] = u'Import operation failed.'
maya.stringTable['y_xgenm_ui_dialogs_xgImportPreset.kImportPresetToSelectedGeometry'] = u'Import Preset'
maya.stringTable['y_xgenm_ui_dialogs_xgImportPreset.kKeepGuideOrientation'] = u'Use original orientations in the world space'
maya.stringTable['y_xgenm_ui_dialogs_xgImportPreset.kMissGroom'] = u'The grooming setting file "%s" is missing from the directory "%s". Default grooming settings will be used for the preset.'
maya.stringTable['y_xgenm_ui_dialogs_xgImportPreset.kNewDescriptionNameForPreset'] = u'New Description Name:'
maya.stringTable['y_xgenm_ui_dialogs_xgImportPreset.kNoGuide'] = u'Place guides manually'
maya.stringTable['y_xgenm_ui_dialogs_xgImportPreset.kPleaseSelectAPolygonSurfaceForPresetTip'] = u'There is no polygon surface (or faces) to apply to.'
maya.stringTable['y_xgenm_ui_dialogs_xgImportPreset.kPosBasedGuideTransfer'] = u'Position based'
maya.stringTable['y_xgenm_ui_dialogs_xgImportPreset.kPresetFileDoesNotExist'] = u"The file doesn't exist."
maya.stringTable['y_xgenm_ui_dialogs_xgImportPreset.kRotateGuideOrientationToNewNormal'] = u'Rotate to align with new surface normals'
maya.stringTable['y_xgenm_ui_dialogs_xgImportPreset.kTransferGuide'] = u'Transfer guides from preset to new target'
maya.stringTable['y_xgenm_ui_dialogs_xgImportPreset.kUVBasedGuideTransfer'] = u'UV based'
