import maya

maya.stringTable['y_xgenm_ui_widgets_xgArchiveFilesUI.kAdd'] = u'Add...'
maya.stringTable['y_xgenm_ui_widgets_xgArchiveFilesUI.kAddAnn'] = u'Add a new archive file to the list.'
maya.stringTable['y_xgenm_ui_widgets_xgArchiveFilesUI.kAddedXarcArchives'] = u'Added .xarc archive(s) have associated archive materials files.\n\nDo you want to import the following archive materials files?\n%s\nWarning: The import file command will destroy the undo stack.'
maya.stringTable['y_xgenm_ui_widgets_xgArchiveFilesUI.kArchive'] = u'Archive:'
maya.stringTable['y_xgenm_ui_widgets_xgArchiveFilesUI.kArchive2'] = u'Archive:'
maya.stringTable['y_xgenm_ui_widgets_xgArchiveFilesUI.kCouldntCreateEmptyPixmap'] = u"Couldn't create empty pixmap"
maya.stringTable['y_xgenm_ui_widgets_xgArchiveFilesUI.kCreate'] = u'Create From Selection...'
maya.stringTable['y_xgenm_ui_widgets_xgArchiveFilesUI.kCreateAnn'] = u'Export selected objects as an archive file that can then be added to this description.'
maya.stringTable['y_xgenm_ui_widgets_xgArchiveFilesUI.kEdit'] = u'Edit...'
maya.stringTable['y_xgenm_ui_widgets_xgArchiveFilesUI.kEditAnn'] = u'Edit the information and preview color of the selected archive file.'
maya.stringTable['y_xgenm_ui_widgets_xgArchiveFilesUI.kEditRightClick'] = u'Edit'
maya.stringTable['y_xgenm_ui_widgets_xgArchiveFilesUI.kErrorWhileReadFile'] = u'Error when reading file:'
maya.stringTable['y_xgenm_ui_widgets_xgArchiveFilesUI.kList'] = u'Show Thumbnails'
maya.stringTable['y_xgenm_ui_widgets_xgArchiveFilesUI.kListAnn'] = u'Display the archive list with thumbnail images.'
maya.stringTable['y_xgenm_ui_widgets_xgArchiveFilesUI.kRemove'] = u'Remove'
maya.stringTable['y_xgenm_ui_widgets_xgArchiveFilesUI.kRemoveAnn'] = u'Remove the selected archive file from the list.'
maya.stringTable['y_xgenm_ui_widgets_xgArchiveFilesUI.kRemoveRightClick'] = u'Remove'
maya.stringTable['y_xgenm_ui_widgets_xgArchiveFilesUI.kThumbnailSizeAnn'] = u'Make the archive thumbnail images larger or smaller.'
maya.stringTable['y_xgenm_ui_widgets_xgArchiveFilesUI.kXgenAddArchives'] = u'XGen Add Archives'
maya.stringTable['y_xgenm_ui_widgets_xgArchiveFilesUI.kXgenEditArchive2'] = u'XGen Edit Archive'
maya.stringTable['y_xgenm_ui_widgets_xgArchiveFilesUI.kXgenImportMaterials'] = u'XGen Import Materials'
maya.stringTable['y_xgenm_ui_widgets_xgArchiveFilesUI.kXgenRemoveArchive'] = u'XGen Remove Archive'
