import maya

maya.stringTable['y_xgenm_ui_fxmodules_xgDirectionalForceFXModuleTab.kCenter'] = u'Center'
maya.stringTable['y_xgenm_ui_fxmodules_xgDirectionalForceFXModuleTab.kCenterAnn'] = u'The center location of ellipsoid. (expression: vector)'
maya.stringTable['y_xgenm_ui_fxmodules_xgDirectionalForceFXModuleTab.kDirectionalForceModifier'] = u'Directional Force Modifier'
maya.stringTable['y_xgenm_ui_fxmodules_xgDirectionalForceFXModuleTab.kMagnitude'] = u'Magnitude'
maya.stringTable['y_xgenm_ui_fxmodules_xgDirectionalForceFXModuleTab.kMagnitudeAnn'] = u'Strength of the force. (expression: float)'
maya.stringTable['y_xgenm_ui_fxmodules_xgDirectionalForceFXModuleTab.kRange'] = u'Range'
maya.stringTable['y_xgenm_ui_fxmodules_xgDirectionalForceFXModuleTab.kRangeAnn'] = u'Determines when the force tapers to zero. (expression: [0, 1])'
maya.stringTable['y_xgenm_ui_fxmodules_xgDirectionalForceFXModuleTab.kXVec'] = u'X Vec'
maya.stringTable['y_xgenm_ui_fxmodules_xgDirectionalForceFXModuleTab.kXVecAnn'] = u'The X vector defining the ellipsoid. (expression: vector)'
maya.stringTable['y_xgenm_ui_fxmodules_xgDirectionalForceFXModuleTab.kYVec'] = u'Y Vec'
maya.stringTable['y_xgenm_ui_fxmodules_xgDirectionalForceFXModuleTab.kYVecAnn'] = u'The Y vector defining the ellipsoid. (expression: vector)'
maya.stringTable['y_xgenm_ui_fxmodules_xgDirectionalForceFXModuleTab.kZVec'] = u'Z Vec'
maya.stringTable['y_xgenm_ui_fxmodules_xgDirectionalForceFXModuleTab.kZVecAnn'] = u'The Z vector defining the ellipsoid. (expression: vector)'
