import maya

maya.stringTable['y_xgenm_ui_fxmodules_xgMeshCutFXModuleTab.kBakeCutData'] = u'Bake Cut Data'
maya.stringTable['y_xgenm_ui_fxmodules_xgMeshCutFXModuleTab.kBakeDir'] = u'Bake Dir'
maya.stringTable['y_xgenm_ui_fxmodules_xgMeshCutFXModuleTab.kBakeDirAnn'] = u'Directory for the baked cut file.'
maya.stringTable['y_xgenm_ui_fxmodules_xgMeshCutFXModuleTab.kBakeOptions'] = u'Bake Options'
maya.stringTable['y_xgenm_ui_fxmodules_xgMeshCutFXModuleTab.kBakingPrimProgress'] = u'Baking primitive cut locations into XPD files.'
maya.stringTable['y_xgenm_ui_fxmodules_xgMeshCutFXModuleTab.kCull'] = u'Cull'
maya.stringTable['y_xgenm_ui_fxmodules_xgMeshCutFXModuleTab.kCutType'] = u'Cut Type'
maya.stringTable['y_xgenm_ui_fxmodules_xgMeshCutFXModuleTab.kCutTypeAnn'] = u'What to do with the primitives after the cut.'
maya.stringTable['y_xgenm_ui_fxmodules_xgMeshCutFXModuleTab.kKeepParam'] = u'Keep Param'
maya.stringTable['y_xgenm_ui_fxmodules_xgMeshCutFXModuleTab.kLiveCut'] = u'Live Cut'
maya.stringTable['y_xgenm_ui_fxmodules_xgMeshCutFXModuleTab.kMeshCutModifier'] = u'Mesh Cut Modifier'
maya.stringTable['y_xgenm_ui_fxmodules_xgMeshCutFXModuleTab.kMeshFile'] = u'Mesh File'
maya.stringTable['y_xgenm_ui_fxmodules_xgMeshCutFXModuleTab.kMeshFileAnn'] = u'Name of the file that contains meshes to cut primitives against.'
maya.stringTable['y_xgenm_ui_fxmodules_xgMeshCutFXModuleTab.kMode'] = u'Mode'
maya.stringTable['y_xgenm_ui_fxmodules_xgMeshCutFXModuleTab.kModeAnn'] = u'Whether to cut primitives in live mode or using the cut data from the cut file.'
maya.stringTable['y_xgenm_ui_fxmodules_xgMeshCutFXModuleTab.kOffset'] = u'Offset'
maya.stringTable['y_xgenm_ui_fxmodules_xgMeshCutFXModuleTab.kOffsetAnn'] = u'Offset on the primitive away from the computed cut point against the cutting surface. (experssion)'
maya.stringTable['y_xgenm_ui_fxmodules_xgMeshCutFXModuleTab.kReparam'] = u'Reparam'
maya.stringTable['y_xgenm_ui_fxmodules_xgMeshCutFXModuleTab.kTestsPerPrim'] = u'Tests Per Prim'
maya.stringTable['y_xgenm_ui_fxmodules_xgMeshCutFXModuleTab.kTestsPerPrimAnn'] = u'Number of equal length segments to slice up the spline primitive when testing for polygon intersection. (int)'
maya.stringTable['y_xgenm_ui_fxmodules_xgMeshCutFXModuleTab.kUseBakedCut'] = u'Use Baked Cut'
