import maya

maya.stringTable['y_xgenm_ui_fxmodules_xgPlaneForceFXModuleTab.kDepth'] = u'Depth'
maya.stringTable['y_xgenm_ui_fxmodules_xgPlaneForceFXModuleTab.kDepthAnn'] = u'Depth behind plane of maximum force. (expression: float)'
maya.stringTable['y_xgenm_ui_fxmodules_xgPlaneForceFXModuleTab.kFalloff'] = u'Falloff'
maya.stringTable['y_xgenm_ui_fxmodules_xgPlaneForceFXModuleTab.kFalloffAnn'] = u'Power of falloff from depth to boundary. (expression: float)'
maya.stringTable['y_xgenm_ui_fxmodules_xgPlaneForceFXModuleTab.kMagnitude'] = u'Magnitude'
maya.stringTable['y_xgenm_ui_fxmodules_xgPlaneForceFXModuleTab.kMagnitudeAnn'] = u'Strength of the force. (expression: float)'
maya.stringTable['y_xgenm_ui_fxmodules_xgPlaneForceFXModuleTab.kPlaneForceModifier'] = u'Plane Force Modifier'
maya.stringTable['y_xgenm_ui_fxmodules_xgPlaneForceFXModuleTab.kPoint1'] = u'Point 1'
maya.stringTable['y_xgenm_ui_fxmodules_xgPlaneForceFXModuleTab.kPoint2'] = u'Point 2'
maya.stringTable['y_xgenm_ui_fxmodules_xgPlaneForceFXModuleTab.kPoint3'] = u'Point 3'
maya.stringTable['y_xgenm_ui_fxmodules_xgPlaneForceFXModuleTab.kPoint4'] = u'Point 4'
maya.stringTable['y_xgenm_ui_fxmodules_xgPlaneForceFXModuleTab.kPointFourAnn'] = u'Location of plane force P4. (expression: vector)'
maya.stringTable['y_xgenm_ui_fxmodules_xgPlaneForceFXModuleTab.kPointOneAnn'] = u'Location of plane force P1. (expression: vector)'
maya.stringTable['y_xgenm_ui_fxmodules_xgPlaneForceFXModuleTab.kPointThreeAnn'] = u'Location of plane force P3. (expression: vector)'
maya.stringTable['y_xgenm_ui_fxmodules_xgPlaneForceFXModuleTab.kPointTwoAnn'] = u'Location of plane force P2. (expression: vector)'
